### ISSUE TITLE
PCB_coco数据 训练报错

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleYOLO#149]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![Snip20230531_2](https://github.com/PaddlePaddle/PaddleYOLO/assets/7626261/5066fb65-e162-41b3-bc8d-27c4f81a0bc7)

配置文件修改：
![Snip20230531_4](https://github.com/PaddlePaddle/PaddleYOLO/assets/7626261/b2c5973e-0e7e-4ca6-892b-2a8bf417230d)

因为报错，所以在358行代码中添加了打印
![Snip20230531_3](https://github.com/PaddlePaddle/PaddleYOLO/assets/7626261/c2119885-003b-4a4f-8a70-b03d258d98fb)

第一个batch有值，第二个batch就成了[]，好纳闷

执行的命令:
```
python tools/train.py -c configs/yolov5u/yolov5up6_s_300e_coco.yml
```

-------------------------------------------
有可能是我有遗漏，也许是本来就有bug。同样的数据集，换成
python tools/train.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml 就可以执行训练

**Comment by nemonameless** [comment]
coco数据集上均没有此类似报错，建议重新检查下数据集制作，排除空标注或不合理标注框，同时reader里去除mosaic再试试
```
mosaic_epoch: &mosaic_epoch -1 
worker_num: 4
TrainReader:
  sample_transforms:
    - Decode: {}
    - MosaicPerspective: {mosaic_prob: 0.0, target_size: *input_size}
   .......
```
