### ISSUE TITLE
Single-class yolov7 training hangs

### ISSUE THREAD

**Issue by danielvandenberg95** [PaddlePaddle/PaddleYOLO#200]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

When training yolo7 (tiny or x) with multiple classes everything works fine, but when training with a single class it hangs on the first epoch.

My config is as follows:

```
EvalDataset: !COCODataSet
  allow_empty: true
  anno_path: annotations/valid.json
  data_fields:
  - image
  dataset_dir: <<my_dataset_dir>>
  image_dir: images
EvalReader:
  batch_size: 2
LearningRate:
  base_lr: 0.0001
TestDataset: !ImageFolder
  anno_path: annotations/valid.json
  dataset_dir: <<my_dataset_dir>>
TestReader:
  batch_size: 2
TrainDataset: !COCODataSet
  allow_empty: false
  anno_path: annotations/train.json
  data_fields:
  - image
  - gt_bbox
  - gt_class
  - is_crowd
  dataset_dir: <<my_dataset_dir>>
  image_dir: images
TrainReader:
  batch_size: 64
_BASE_:
- /data/repos/PaddleYOLO/configs/yolov7/yolov7_tiny_300e_coco.yml
eval: true
find_unused_parameters: false
log_iter: 1
metric: COCO
num_classes: 1
output_eval: <<my_output_dir>>202311130842/eval
save_dir: <<my_output_dir>>202311130842
snapshot_epoch: 2
use_gpu: true
weights: <<my_output_dir>>202311130842
```
