### ISSUE TITLE
yolov5s 开启--eval, 验证会卡住

### ISSUE THREAD

**Issue by Tongfengyu** [PaddlePaddle/PaddleYOLO#39]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/82866148/193400164-fb198887-1966-4e4a-a158-01c156cfa85d.png)
YOLOv5 reader 按照默认配置

**Comment by Tongfengyu** [comment]
单独验证也会卡住

**Comment by nemonameless** [comment]
请按模板提问谢谢，环境版本是多少？几个显卡总bs是多少，只训1 epoch没必要eval，等10epoch再看
https://github.com/PaddlePaddle/PaddleYOLO/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml

**Comment by Tongfengyu** [comment]
-OS: Linux
-PaddlePaddle: paddlepaddle-gpu 2.3.1
-PaddleYOLO: release/2.4 和2.5
-Python: 3.7.13
-CUDA:  11.2
-CUDNN: 8.1
-GCC: 7.5.0

**Comment by Tongfengyu** [comment]
单卡。训练bs：32，验证bs：8

**Comment by Tongfengyu** [comment]
![image](https://user-images.githubusercontent.com/82866148/193996426-e80ace38-f098-4517-9a24-17f1296d59ef.png)
为什么验证过程会那么慢

**Comment by nemonameless** [comment]
总bs=32还可以不算太小。现在是多少epoch一次eval呢？确定加载了coco权重做预训练吗？
大概率是训练早期低质量框太多基本耗在nms。nms参数可以自己调，score_threshold设置高点速度会极快，对mAP影响也不算太大。
```
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.1
    nms_threshold: 0.65
```
